//default theme 
if(UI.Platform.ARCH=="mac"){
	UI.font_name="LucidaGrande,res/fonts/opensans.ttf"
	UI.eng_font_name="res/fonts/opensans.ttf,!"
}else{
	UI.font_name="res/fonts/opensans.ttf"
	UI.eng_font_name="res/fonts/opensans.ttf,!"
}

UI.CustomTheme=function(){
	var C=UI.current_theme_color;
	var C_dark=UI.lerp_rgba(C,0xff000000,0.15)
	var C_sel=UI.lerp_rgba(C,0xffffffff,0.66)
	return {
		tooltip:{
			font:UI.Font(UI.font_name,24,-50),
			padding:8,
			spacing:8,
			color:0xffffffff,
			round:8,
			border_color:0xff000000,
			border_width:1,
			text_color:0xff000000,
			shadow_size:6,
			shadow_color:0xaa000000,
			triangle_font:UI.Font(UI.icon_font_name,16,0),
			triangle_font2:UI.Font(UI.icon_font_name,16,500),
		},
		button:{
			transition_dt:0.1,
			round:0.1,border_width:1,padding:0,
			font:UI.Font(UI.font_name,20,-50),
			icon_font:UI.Font(UI.icon_font_name,18),
			$:{
				out:{
					//border_color:0xff444444,color:0xffffffff,
					border_color:0xff444444,color:[{x:0,y:0,color:0xffffffff},{x:0,y:1,color:0xffe8e8e8}],
					icon_color:0xff000000,
					text_color:0xff000000,
				},
				over:{
					border_color:C,color:C,
					icon_color:0xffffffff,
					text_color:0xffffffff,
				},
				down:{
					border_color:C_dark,color:C_dark,
					icon_color:0xffffffff,
					text_color:0xffffffff,
				},
			}
		},
		check_button:{
			transition_dt:0.1,
			round:0,border_width:2,padding:12,
			icon_color:0xff444444,
			text_color:0xff444444,
			$:{
				out:{
					border_color:C&0x00ffffff,color:0x00ffffff,
				},
				over:{
					border_color:C,color:0x00ffffff,
				},
				down:{
					border_color:C_dark,color:0x00ffffff,
				},
				////////////////////
				checked_out:{
					border_color:C&0x00ffffff,color:C_sel,
				},
				checked_over:{
					border_color:C,color:C_sel,
				},
				checked_down:{
					border_color:C_dark,color:C_sel,
				},
			}
		},
		sub_window:{
			transition_dt:0.1,
			round:0,border_width:2,
			padding:4,h_caption:24,
			/////////////////
			layout_direction:"inside",layout_align:'left',layout_valign:'up',
			/////////////////
			font:UI.Font(UI.font_name,20,100),
			color:0xffffffff,border_color:C,border_width:2,
			caption_color:C,text_color:0xffdddddd,
			button_style:{
				transition_dt:0.1,
				round:0,border_width:2,padding:8,
				border_width:0,color:0,
				text_color:0xffdddddd,
				font:UI.Font(UI.font_name,20,100),
				$:{
					out:{
						text_color:0xffdddddd
					},
					over:{
						text_color:0xffffffff,
					},
					down:{
						text_color:0xffffffff,
					},
				}
			},
		},
		tab_label:{
			transition_dt:0.1,
			shadow_size:8,
			hotkey_font:UI.Platform.ARCH=="mac"?UI.Font(UI.font_name,10,0):UI.Font(UI.font_name,12,0),
			font:UI.Platform.ARCH=="mac"?UI.Font(UI.font_name,22,-50):UI.Font(UI.font_name,24,-50), padding:16,
			$:{
				active:{
					text_color:0xffffffff,
					color:C,
					shadow_color:0xaa000000,
				},
				inactive:{
					text_color:0xff000000,
					color:C&0x00f0f0f0,
					shadow_color:0x00000000, 
				},
			}
		},
		tabbed_document:{
			transition_dt:0.1,
			h_caption:32, h_bar:4, color:0xffbbbbbb, border_color:C,
			w_menu_button:26,
			h_menu_button:26,
			padding:4,
			menu_bar_color:[{x:0,y:0,color:0xffffffff},{x:0,y:1,color:0xffe8e8e8}],
			menu_bar_border_width:0,
			menu_bar_border_color:0xffaaaaaa,
			menu_bar_shadow_size:8,
			menu_bar_shadow_color:0xaa000000,
			menu_button_style:{
				transition_dt:0.25,
				round:0,padding:0,
				color:0,
				$:{
					out:{
						text_color:0xffaaaaaa,
					},
					over:{
						text_color:C,
					},
					down:{
						text_color:UI.lerp_rgba(C,0xff000000,0.2),
					},
					checked_out:{
						text_color:C,
					},
					checked_over:{
						text_color:C,
					},
					checked_down:{
						text_color:UI.lerp_rgba(C,0xff000000,0.2),
					},
				}
			},
		},
		save_dialog:{
			transition_dt:0.1,
			color:0x00d0d0d0,
			$:{
				active:{
					color:0x7f000000,
				},
				inactive:{
					color:0x00000000,
				},
			},
			///////////
			shadow_color:0xff000000,
			shadow_size:32,
			border_color:0xff444444,
			border_width:0,
			round_dlg_rect:32,
			space_dlg_rect_x:48,
			space_dlg_rect:32,
			color_dlg_rect:0xf0ffffff,
			font_text:UI.Font(UI.font_name,40,-50),
			text_color:0xff000000,
			font_buttons:UI.Font(UI.font_name,28,-50),
			space_middle:32,
			space_button:80,
			h_button:48,
			good_button_style:{
				transition_dt:0.1,
				round:32,border_width:0,padding:24,
				$:{
					out:{
						color:[{x:0,y:0,color:UI.lerp_rgba(C,0xffffffff,0.2)},{x:0,y:1,color:UI.lerp_rgba(C,0xff000000,0.1)}],
						icon_color:0xfff0f0f0,
						text_color:0xfff0f0f0,
					},
					over:{
						color:[{x:0,y:0,color:UI.lerp_rgba(C,0xffffffff,0.4)},{x:0,y:1,color:UI.lerp_rgba(C,0xffffffff,0.1)}],
						icon_color:0xffffffff,
						text_color:0xffffffff,
					},
					down:{
						color:[{x:0,y:0,color:UI.lerp_rgba(C,0xffffffff,0.1)},{x:0,y:1,color:UI.lerp_rgba(C,0xff000000,0.2)}],
						icon_color:0xfff0f0f0,
						text_color:0xfff0f0f0,
					},
				}
			},
			bad_button_style:{
				transition_dt:0.1,
				round:32,border_width:0,padding:24,
				$:{
					out:{
						color:[{x:0,y:0,color:0xff999999},{x:0,y:1,color:0xff666666}],
						icon_color:0xfff0f0f0,
						text_color:0xfff0f0f0,
					},
					over:{
						color:[{x:0,y:0,color:0xffaaaaaa},{x:0,y:1,color:0xff7f7f7f}],
						icon_color:0xffffffff,
						text_color:0xffffffff,
					},
					down:{
						color:[{x:0,y:0,color:0xff888888},{x:0,y:1,color:0xff555555}],
						icon_color:0xfff0f0f0,
						text_color:0xfff0f0f0,
					},
				}
			},
		},
		box_document:{
			border_color:(0xccffffff&C),border_width:2,w_snapping_line:2,
			color:(0x44ffffff&C),
		},
		txtx_editor:{
			border_color:0xff000000,border_width:2,
			color:0xffffffff,
		},
		color_picker:{
			w_text:16,w_slider:128,w_edit:54,
			h_slider:12,
			h_edit:32,
			h_space:24,
			padding:8,
			border_width:1.5,
			border_color:0xff444444,
			text_color:0xff000000,
			font:UI.Font(UI.font_name,24),
		},
		demo_document:{
			thumbnail_style:{
				border_color:0xff000000,
				border_width:1.5,
				text_color:0xff000000,
				sel_border_color:C,
				sel_border_width:3,
				sel_text_color:C,
				font:UI.Font(UI.font_name,24),
				text_padding:4,
			},
			new_page_button_style:{
				transition_dt:0.1,
				round:0,border_width:3,padding:0,color:0,
				font:UI.Font(UI.font_name,72,-50),
				$:{
					out:{
						border_color:0x80000000,
						icon_color:0x80000000,
						text_color:0x80000000,
					},
					over:{
						border_color:0xaa000000,
						icon_color:0xaa000000,
						text_color:0xaa000000,
					},
					down:{
						border_color:0xaa000000,
						icon_color:0xaa000000,
						text_color:0xaa000000,
					},
				},
			},
		},
		style_item:{
			border_color:0,border_width:0,
			color:0x00000000,
			padding:4,
			$:{
				focus:{
					color:C_sel,
				},
				blur:{
					color:0x00000000,
				}
			}
		},
		code_editor:{
			editor_style:{
				//wrap_width:1536,
				//font:UI.Font("res/fonts/inconsolata.ttf",36),
				//font_emboldened:UI.Font("res/fonts/inconsolata.ttf",36,200),
				//tex_font:UI.Font("res/fonts/cmunrm.ttf",36),
				//tex_font_emboldened:UI.Font("res/fonts/cmunrm.ttf",36,200),
				//font_tilde:UI.Font(UI.icon_font_name,36,100),
				font:UI.Font("res/fonts/inconsolata.ttf",28),
				font_emboldened:UI.Font("res/fonts/inconsolata.ttf",28,200),
				tex_font:UI.Font("res/fonts/cmunrm.ttf",28,0),
				tex_font_emboldened:UI.Font("res/fonts/cmunrm.ttf",28,200),
				font_tilde:UI.Font(UI.icon_font_name,28,100),
				//font:UI.Font("res/fonts/inconsolata.ttf",32),
				//font_emboldened:UI.Font("res/fonts/inconsolata.ttf",32,200),
				//tex_font:UI.Font("res/fonts/cmunrm.ttf",32),
				//tex_font_emboldened:UI.Font("res/fonts/cmunrm.ttf",32,200),
				//font_tilde:UI.Font(UI.icon_font_name,32,100),
				color:0xff000000,
				color2:0xff000000,
				color_normal:0xff000000,
				color_overlay:0xff7f7f7f,
				color_string:0xff1c1aa3,
				color_number:0xff1c1aa3,
				color_comment:0xff2ca033,
				color_keyword:0xffb4771f,
				color_type:0xffbc470f,
				color_symbol:0xff7f7f7f,
				color_symbol2:0xff7f7f7f,
				color_meta:0xff9a3d6a,
				/////////////
				color_key_decl_func:0xff845717,//0xff5a3b0f,
				color_key_decl_class:0xffbc470f,
				color_key_decl_macro:0xff9a3d6a,
				/////////////
				//virtual hyphen for tex-like files, should be even less obvious than normal symbols
				color_hyphen:0xffaaaaaa,
				color_tilde_spell_error:0xff1c1aa3,
				color_tilde_compiler_error:0xff1c1aa3,
				color_tilde_compiler_warning:0xff2ca033,
				/////////////
				color_completing_bracket:0x80999999,
				color_auto_edit_range_highlight:0x4099ffff,
				color_strikeout:0x80444444,
				color_virtual_diff_bold:0xff1c1aa3,
				/////////////
				bgcolor_ellipsis:[{x:0,y:0,color:0xffffffff},{x:1,y:1,color:C_sel}],
				w_ellipsis:32,
				padding_ellipsis:2,
				h_ellipsis:20,
				/////////////
				bgcolor_selection:C&0x55ffffff,
				tab_width:4,
				scroll_transition_dt:0.075,
				/////////////
				//rectex_styles:[{color:0,w:32,h:32,round:8,border_width:3,border_color:0xff1c1aa3}],
				rectex_styles:[{color:0x7f00ffff,w:32,h:32,round:8,border_width:-8}],
			},
			bgcolor:0xffe8e8e8,
			padding:6,
			separator_color:0xff999999,
			///////
			//show_top_hint:1,
			top_hint_shadow_color:0x7f000000,
			top_hint_shadow_size:8,
			top_hint_border_width:2,
			top_hint_border_color:0xffaaaaaa,
			top_hint_max_lines:3,
			top_hint_max_levels:20,
			x_scroll_shadow_color:0x7f000000,
			x_scroll_shadow_size:8,
			///////
			//show_line_numbers:1,
			line_number_font:UI.Platform.ARCH=="mac"?UI.Font(UI.font_name,12,-50):UI.Font(UI.font_name,14,-50),
			line_number_bgcolor:0xffd0d0d0,
			line_number_color:0xff7f7f7f,
			line_number_color_focus:0xff000000,
			color_cur_line_highlight:0x55ffffff,
			///////
			bookmark_font:UI.Platform.ARCH=="mac"?UI.Font(UI.font_name,10,200):UI.Font(UI.font_name,12,200),
			bookmark_color:[{x:0,y:0,color:0xffffffff},{x:1,y:1,color:C_sel}],
			bookmark_text_color:C,
			//bookmark_shadow:0xff000000,
			bookmark_border_color:C,
			bookmark_scroll_bar_marker_size:2,
			///////
			//color_diff_tag:[{x:0,y:0,color:0xff2ca033&0xffffff},{x:1,y:0,color:0xff2ca033}],
			color_diff_tag:[{x:0,y:0,color:0x002ca033},{x:1,y:0,color:0xff2ca033}],
			sbar_diff_color:(0xff2ca033),
			///////
			//show_minimap:(UI.Platform.ARCH=="linux32"||UI.Platform.ARCH=="android"||UI.Platform.ARCH=="ios")?0:1,
			minimap_font_height:6,
			minimap_page_shadow:0x1f000000,
			minimap_page_border_width:2,
			minimap_page_border_color:0xffaaaaaa,
			sbar_eye_font:UI.Font(UI.icon_font_name,12,200),
			sbar_page_shadow:0xaa444444,
			sbar_page_border_color:0xff444444,
			sbar_page_border_width:1,
			w_minimap:128,
			///////
			disclaimer_transition_dt:0.1,
			disclaimer_color:0xff1c1aa3,
			h_find_bar:32,
			find_bar_bgcolor:0xffffffff,
			find_bar_color:0xffe8e8e8,
			find_bar_round:8,
			find_bar_padding:4,
			find_bar_hint_color:0xff7f7f7f,
			find_bar_shadow_color:0x7f000000,
			find_bar_shadow_size:8,
			find_bar_hint_font:UI.Font(UI.font_name,20,-50),
			find_bar_button_size:28,
			find_bar_editor_style:{
				font:UI.Font("res/fonts/inconsolata.ttf",20),
				tex_font:UI.Font("res/fonts/cmunrm.ttf",20),
				font_emboldened:UI.Font("res/fonts/inconsolata.ttf",20,200),
				tex_font_emboldened:UI.Font("res/fonts/cmunrm.ttf",20,200),
				//font_tilde:UI.Font(UI.icon_font_name,28,100),
				font_tilde:UI.Font(UI.icon_font_name,26,100),
				color:0xff000000,
				color_overlay:0xff000000,
				color_string:0xff1c1aa3,
				color_number:0xff1c1aa3,
				color_comment:0xff2ca033,
				color_keyword:0xffb4771f,
				color_type:0xffbc470f,
				color_symbol:0xff7f7f7f,
				rectex_styles:[{color:0}],
				bgcolor_selection:C&0x55ffffff,
				tab_width:4,
			},
			find_item_scale:0.8,
			find_item_expand_current:4,//in lines
			find_item_separation:6,
			find_item_border_width:0,
			find_item_border_color:0xff444444,
			find_item_shadow_color:0x7f000000,
			find_item_shadow_size:4,
			find_mode_bgcolor:0xffc0c0c0,
			//find_item_replace_highlight_color:0x55007fff,
			find_message_font:UI.Font(UI.font_name,32,-50),
			find_message_color:0xff444444,
			///////
			show_auto_completion:1,
			accands_font:UI.Font(UI.font_name,22,-50),
			accands_id_font:UI.Font(UI.font_name,12,200),
			accands_padding:24,
			accands_left_padding:14,
			accands_sel_padding:2,
			accands_shadow_color:0x7f000000,
			accands_shadow_size:8,
			accands_bgcolor:0xffffffff,
			accands_round:4,
			accands_border_width:0,
			accands_border_color:0xff000000,
			accands_text_color:0xff000000,
			accands_text_sel_color:0xffffffff,
			accands_sel_bgcolor:C,
			accands_n_shown:5,
			autoedit_button_size:24,
			autoedit_button_padding:2,
			//w_accands:512,
			h_accands:32,
			///////
			w_scroll_bar:20,
			scroll_bar_style:{
				transition_dt:0.1,
				//bgcolor:0xffd0d0d0,
				round:0,
				padding:0,
				szbar_min:32,
				middle_bar:{
					w:12,h:12,
					round:6,
					color:0,
					border_color:0,
				},
				icon_color:0xff999999,
				text_color:0xff999999,//dummy
				$:{
					out:{
						icon_color:[{x:0,y:0,color:0x00999999},{x:1,y:1,color:0x00666666}],
						text_color:0x00999999,//dummy
					},
					over:{
						icon_color:[{x:0,y:0,color:0xff999999},{x:1,y:1,color:0xff666666}],
						text_color:0xff999999,//dummy
					},
				},
			},
			///////
			w_notification:340,
			dx_shake_notification:-300,
			///////
			sxs_shadow_size:6,
			sxs_shadow_color:0xaa000000,
			///////
			status_bar_bgcolor:[{x:0,y:0,color:0xffffffff},{x:0,y:1,color:0xffd0d0d0}],
			status_bar_font:UI.Font(UI.font_name,20,-50),
			status_bar_padding:4,
			status_bar_text_color:0xff444444,
			///////
			wrap_bar_size:3,
			wrap_bar_region_size:8,
			wrap_bar_color:0x2f000000,
		},
		code_editor_notification:{
			transition_dt:0.1,
			padding:6,
			w_icon:24,
			w_text:300,
			shadow_size:8,
			shadow_color:0xff000000,
			color:0xffffffff,
			border_color:0xff000000,
			border_width:0,
			round:4,
			text_color:0xff444444,
			progress_color:C_sel,
			font:UI.Font(UI.font_name,20,0),
			icon_color:0xff000000,
			icon_font:UI.Font('res/fonts/iconfnt.ttf,!',20),
			icon:'告',
			//////////
			k_shake:400,
			damping_shake:8,
			x_min_shake:0.5,
			dx_min_shake:0.5,
		},
		sxs_build_output:{
			border_width:0,
			color:0xffffffff,
			editor_style:{
				font:UI.Font("res/fonts/inconsolata.ttf",16,-50),
				font_emboldened:UI.Font("res/fonts/inconsolata.ttf",16,100),
				scroll_transition_dt:0.1,
				bgcolor_selection:C_sel,
				color:0xff000000,
				state_handlers:["renderer_programmer","colorer_programmer","line_column_unicode","seeker_indentation"],
				read_only:1,
				$:{
					focus:{
						bgcolor_selection:C_sel,
					},
					blur:{
						bgcolor_selection:0xffcccccc,
					},
				}
			},
		},
		sxs_new_page:{
			color:0xffffffff,
			border_color:0xff000000,
			border_width:0,
			round:0,
			//////////////////////
			h_find_bar:32,
			find_bar_bgcolor:0xffffffff,
			find_bar_color:0xffe8e8e8,
			find_bar_round:8,
			find_bar_padding:4,
			find_bar_hint_color:0xff7f7f7f,
			find_bar_shadow_color:0x7f000000,
			find_bar_shadow_size:8,
			find_bar_hint_font:UI.Font(UI.font_name,20,-50),
			find_bar_button_size:28,
			find_bar_editor_style:{
				font:UI.Font("res/fonts/inconsolata.ttf",20),
				color:0xff000000,
				bgcolor_selection:C&0x3fffffff,
				tab_width:4,
			},
		},
		binary_editor:{
			font:UI.Font("res/fonts/inconsolata.ttf",24),
			font_edit:UI.Font("res/fonts/inconsolata.ttf",16),
			font_goto:UI.Font("res/fonts/inconsolata.ttf",16),
			mouse_wheel_speed:4,
			edit_padding:8,
			edit_bgcolor:0xffffffff,
			edit_border_width:2,
			edit_border_color:C,
			edit_round:4,
			edit_shadow_color:0x7f000000,
			edit_shadow_size:8,
			edit_rect_color:0xaa8adfb2,
			edit_rect_blur:8,
			line_number_font:UI.Font("res/fonts/inconsolata.ttf",14,200),
			line_number_font_small:UI.Font("res/fonts/inconsolata.ttf",8,200),
			line_number_bgcolor:0xffd0d0d0,
			line_number_color:0xff7f7f7f,
			line_number_color_focus:0xff000000,
			caret_width:2,
			caret_color:0xff000000,
			caret_flicker:500,
			text_color:0xff000000,
			bgcolor:0xffe8e8e8,
			bgcolor_selection:C&0x55ffffff,
			separator_color:0xff999999,
			minimap_padding:12,
			minimap_page_shadow:0x55000000,
			minimap_page_border_width:2,
			minimap_page_border_color:0xffaaaaaa,
			sxs_shadow_size:6,
			sxs_shadow_color:0xaa000000,
			sxs_bgcolor:0xffffffff,
			font_panel:UI.Font(UI.font_name,24),
			font_panel_icon:UI.Font(UI.icon_font_name,22),
			font_panel_fixed:UI.Font("res/fonts/inconsolata.ttf",22),
			text_color_panel:0xff000000,
			w_panel:232,
			color_choices:[
				0xffb4771f,0xff2ca033,0xff1c1ae3,0xff007fff,0xff9a3d6a,
				//0xffe3cea6,0xff8adfb2,0xff999afb,0xff6fbffd,0xffd6b2ca,
				0xff00aaaa,0xff8888b8,0xff000080,0xff7f7f7f,0xff000000],
			font_error:UI.Font(UI.font_name,40),
			error_color:0xff444444,
		},
		file_item:{
			h:56,h_dense:32,
			h_icon:48,
			icon_font:UI.Font(UI.icon_font_name,48),
			h_icon_dense:28,
			icon_font_dense:UI.Font(UI.icon_font_name,28),
			h_icon_git:16,
			icon_font_git:UI.Font(UI.icon_font_name,16),
			dir_icon_color:0xffb4771f,
			file_icon_color:0xff444444,
			name_font_size:UI.Platform.ARCH=="mac"?20:24,
			name_font:UI.Platform.ARCH=="mac"?UI.Font(UI.font_name,20,-50):UI.Font(UI.font_name,24,-50),
			name_font_bold:UI.Platform.ARCH=="mac"?UI.Font(UI.font_name,20,100):UI.Font(UI.font_name,24,100),
			misc_font:UI.Platform.ARCH=="mac"?UI.Font(UI.font_name,16,-50):UI.Font(UI.font_name,18,-50),
			name_color:0xff000000,
			misc_color:0xff7f7f7f,
			basepath_color:0xffcccccc,
			sel_bgcolor:C,
			sel_file_icon_color:0xffffffff,
			sel_name_color:0xffffffff,
			sel_misc_color:0xffcccccc,
			sel_basepath_color:0xffcccccc,
			tag_padding:4,
			tag_round:8,
			tag_border_width:0,
			color_git_untracked:0xff9a3d6a,
			color_git_conflicted:0xff1c1ae3,
			color_git_new:0xff2ca033,
			color_git_modified:UI.lerp_rgba(0xff000000,0xff1c1ae3,0.5),
			button_style:{
				transition_dt:0.1,
				round:0.1,border_width:1,padding:4,
				font:UI.Font(UI.font_name,24,-50),
				icon_font:UI.Font(UI.icon_font_name,18),
				$:{
					out:{
						//border_color:0xff444444,color:0xffffffff,
						border_color:0,color:[{x:0,y:0,color:C},{x:0,y:1,color:C}],
						icon_color:0xffffffff,
						text_color:0xffffffff,
					},
					over:{
						border_color:0xff444444,color:[{x:0,y:0,color:0xffffffff},{x:0,y:1,color:0xffe8e8e8}],
						icon_color:0xff000000,
						text_color:0xff000000,
					},
					down:{
						border_color:0xff7f7f7f,color:[{x:0,y:0,color:0xff7f7f7f},{x:0,y:1,color:0xff7f7f7f}],
						icon_color:0xff000000,
						text_color:0xff000000,
					},
				}
			},
		},
		top_menu:{
			//nothing
		},
		top_menu_item:{
			font:UI.Platform.ARCH=="mac"?UI.Font(UI.font_name,20,-50):UI.Font(UI.font_name,22,-50),
			padding:8,
			$:{
				active:{
					color:C,
					text_color:0xffffffff,
				},
				inactive:{
					color:0,
					text_color:0xff000000,
				},
			},
		},
		fancy_menu:{
			color:0xffe8e8e8,
			border_color:0xff444444,
			border_width:1,round:1,
			shadow_color:0xaa000000,
			shadow_size:12,
			///////////
			font:UI.Platform.ARCH=="mac"?UI.Font(UI.font_name,20,-50):UI.Font(UI.font_name,22,-50),
			text_color:0xff000000,
			text_sel_color:0xffffffff,
			icon_color:C,
			hotkey_color:0xff7f7f7f,
			hotkey_sel_color:0xffaaaaaa,
			sel_bgcolor:C,
			///////////
			vertical_padding:4,
			side_padding:8,
			column_padding:32,
			button_padding:4,
			///////////
			h_separator:8,
			h_separator_fill:1,
			separator_color:0xffd0d0d0,
			h_menu_line:32,
			h_button:28,
			w_icon:24,
			checkbox_bgcolor:[{x:0,y:0,color:0xffffffff},{x:0,y:1,color:0xffe8e8e8}],
			button_style:{
				transition_dt:0.1,
				round:0.1,border_width:1,padding:0,
				font:UI.Font(UI.font_name,20,-50),
				icon_font:UI.Font(UI.icon_font_name,18),
				$:{
					out:{
						//border_color:0xff444444,color:0xffffffff,
						border_color:0xff444444,color:[{x:0,y:0,color:0xffffffff},{x:0,y:1,color:0xffe8e8e8}],
						icon_color:0xff000000,
						text_color:0xff000000,
					},
					over:{
						border_color:C,color:C,
						icon_color:0xffffffff,
						text_color:0xffffffff,
					},
					down:{
						border_color:C_dark,color:C_dark,
						icon_color:0xffffffff,
						text_color:0xffffffff,
					},
					checked_out:{
						border_color:C,color:C,
						icon_color:0xffffffff,
						text_color:0xffffffff,
					},
					checked_over:{
						border_color:C,color:C,
						icon_color:0xffffffff,
						text_color:0xffffffff,
					},
					checked_down:{
						border_color:C,color:C,
						icon_color:0xffffffff,
						text_color:0xffffffff,
					},
				}
			},
		},
		scroll_bar:{
			transition_dt:0.1,
			//bgcolor:0xffd0d0d0,
			round:0,
			padding:0,
			szbar_min:32,
			middle_bar:{
				w:8,h:8,
				round:6,
				color:[{x:0,y:0,color:0xff999999},{x:1,y:1,color:0xff666666}],
				border_color:0,
			},
			text_color:0xff999999,//dummy
		},
		sxs_options_page:{
			border_width:0,
			color:0xffe8e8e8,
			categories:[
				"Display","Controls","Editing","Tools",
				"About","Open Source Licenses","Font Licenses"],
			category_icons:["眼","设","换","Ｕ","单","プ","写"],
		},
		feature_item:{
			h_first:72,
			h_normal:36,
			icon_font:UI.Font(UI.icon_font_name,20),
			icon_fontb:UI.Font(UI.icon_font_name,20,100),
			font:UI.Font(UI.font_name,24),
			text_color:0xff000000,
			icon_color:0xff000000,//C,
			text_color_license:0xff7f7f7f,
			caption_font:UI.Font(UI.font_name,28),
			caption_icon_font:UI.Font(UI.icon_font_name,28),
			caption_color:0xffffffff,
			caption_border_color:0xff000000,
			caption_border_width:1,
			caption_shadow_size:6,
			caption_shadow_color:0xaa000000,
			caption_text_color:0xff000000,
			caption_icon_color:0xff7f7f7f,
		},
	};
};

UI.ApplyTheme(UI.CustomTheme())
